parameters:
  imageName: ''  # defaults for any parameters that aren't specified
  dockerId: ''
  dockerpswd: ''

job: docker_push
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: docker tag $(imageName) $(dockerId).azurecr.io/$(imageName)
    displayName: Tag the image
  - script: |
      docker login -u $(dockerId) -p $(dockerpswd) $(dockerId).azurecr.io
      docker push $(dockerId).azurecr.io/$(imageName)
    displayName: Auth to registry and push