# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
name: $(build.buildId)
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - apis/trips/*
    - azure-pipelines/trips*
    exclude:
    - README.md
jobs:
- job: test
  pool:
    vmImage: 'Ubuntu 16.04'
  variables: 
    testProj: ''
  steps:
  - script: echo TODO

- job: docker_build
  pool:
    vmImage: 'Ubuntu 16.04'
  dependsOn: test
  condition: succeeded()
  variables:
    imageName: 'trips:$(build.buildId)'
    dockerfilePath: 'apis/trips/Dockerfile'
    dockerContext: 'apis/trips/'
  steps:
  - template: templates/docker-build.steps.yml
    parameters:
      dockerfilePath: '$(dockerfilePath)'
      imageName: '$(imageName)'
      dockerContext: '$(dockerContext)'
  - template: templates/docker-push.steps.yml
    parameters:
      imageName: '$(imageName)'
      dockerId: '$(dockerId)'
      dockerpswd: '$(dockerpswd)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'apis/trips/helm' 
      artifactName: 'helm' 
      publishLocation: 'Container' # Options: container, filePath
